# Generated by Django 5.2.1 on 2025-05-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ManyToManyField(blank=True, null=True, to='brsapp.route'),
        ),
    ]
